# Generated by Django 4.2.5 on 2023-09-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0024_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('50ML', '50ML'), ('6ML 12ML', '6ML 12ML'), ('6ML', '6ML'), ('12ML', '12ML')], max_length=20),
        ),
    ]
